<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.1</Version>
    <PackageId>WmfDotNet</PackageId>
    <Description>Library to read and rasterize WMF (Windows Metafile Format) files</Description>
    <Authors>GrimaceOfDespair</Authors>
    <RepositoryUrl>https://github.com/GrimaceOfDespair/wmfdotnet</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NGraphics" Version="0.9.24" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.2" />
  </ItemGroup>

</Project>
